- name: Configure {{ component }}   # Parameterizing the all components
  #hosts: "{{ component }}"
  hosts: localhost
  connection: local
  become: yes
  roles:                # This will automatically load a folder called roles in current working directory and check for tasks and files.
  - "{{ component }}"