- name: Configure {{ component }}   # Parameterizing the all components
  hosts: "{{ component }}"
  become: yes
  # vars_files:
  # - vault/mysql.yaml
  roles:                # This will automatically load a folder called roles in current working directory and check for tasks and files.
  - "{{ component }}"